# Generated by Django 4.1.3 on 2022-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_comentarios_id_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='categoria_actividad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
